<?php
/*
 * UpSoonXML v 0.9
 * https://github.com/rodrigomuniz/upSoonXML
 *
 * Copyright 2010, Rodrigo Muniz - @rdmuniz / Wenetus Interactive http://wenetus.com
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 */

// ======================================================================
// ! Read "01.quick-instructions.txt" for a quick guide   
// ! Do NOT edit this file so you can upgrade to a new version more easily
// ======================================================================

// Let's trim the mess
// -----------------------------
$dbName 	=	 trim($dbName);
$yourKey 	=	 trim($yourKey);
$siteName 	=	 trim($siteName);
$logo 		=	 trim($logo);
$when 		=	 trim($when);
$gaUA 		=	 trim($gaUA);
$myLang 	=	 trim($myLang);

// ================= 
// ! Valid e-mail?   
// ================= 
//from: http://www.linuxjournal.com/article/9585
function check_email_address($email) {
// First, we check that there's one @ symbol, 
// and that the lengths are right.
	if (!ereg("^[^@]{1,64}@[^@]{1,255}$", $email)) {
	// Email invalid because wrong number of characters 
	// in one section or wrong number of @ symbols.
	return false;
	}
// Split it into sections to make life easier
	$email_array = explode("@", $email);
	$local_array = explode(".", $email_array[0]);
	for ($i = 0; $i < sizeof($local_array); $i++) {
	if
	(!ereg("^(([A-Za-z0-9!#$%&'*+/=?^_`{|}~-][A-Za-z0-9!#$%&'*+/=?^_`{|}~\.-]{0,63})|(\"[^(\\|\")]{0,62}\"))$",
	$local_array[$i])) {
	  return false;
	}
	}
// Check if domain is IP. If not, 
// it should be valid domain name
	if (!ereg("^\[?[0-9\.]+\]?$", $email_array[1])) {
	$domain_array = explode(".", $email_array[1]);
		if (sizeof($domain_array) < 2) {
		    return false; // Not enough parts to domain
		}
		for ($i = 0; $i < sizeof($domain_array); $i++) {
		  if (!ereg("^(([A-Za-z0-9][A-Za-z0-9-]{0,61}[A-Za-z0-9])|([A-Za-z0-9]+))$",
		$domain_array[$i])) {
		    return false;
		  }
		}
	}
return true;
}


// ========= 
// ! Token   
// ========= 
function auth_token($key) {  
	return md5(session_id() . $key);
}
function is_token_valid($token, $key) {
	return $token == md5(session_id() . $key);
}


// ============= 
// ! LANGUAGES   
// ============= 
if ($myLang == "en") 		{	//English

$lang['xmlFileWarning'] 	= 'OH NO. The XML file to store subscribers could not be found. Try reading the instructions file.';
$lang['emptyEmail'] 		= 'Please fill your e-mail address';
$lang['invalidEmail'] 		= 'Please check your typing.';
$lang['invalidEmail2'] 		= 'is not a valid e-mail address.';
$lang['existingEmail'] 		= 'Email address';
$lang['existingEmail2'] 	= 'is already in our list and will be notified.';
$lang['emptyName'] 			= 'Please fill your name';
$lang['newSite'] 			= 'New site';
$lang['soon'] 				= 'soon…';
$lang['close'] 				= 'Close';
$lang['success'] 			= 'Yay! You are now subscribed and will be notified when the site is up and running.';
$lang['connectError'] 		= 'There was a server comunication problem. Are you conected to the internet? Please try again.';
$lang['logoAlt'] 			= 'Logo';
$lang['titleSoon'] 			= 'Just a bit more!';
$lang['titleH2'] 			= "<strong>$siteName</strong> new site is almost ready.";
$lang['titleH2Date'] 		= "Expected to air on $when.";
$lang['legend'] 			= "Want to be notified when we launch?";
$lang['email'] 				= "E-mail";
$lang['spamAlert'] 			= "We guarantee to use your e-mail only for notification. We hate SPAM as much as you do.";
$lang['name'] 				= "Name";
$lang['optional'] 			= "Optional";
$lang['submit'] 			= "Yes. I want to be notified.";

}


if ($myLang == 'pt_BR') 	{	//Português do Brasil

$lang['xmlFileWarning'] 	= 'OH NÃO. O arquivo XML para armazenar os assinantes não foi encontrado. Tente ler o arquivo de instruções.';
$lang['emptyEmail'] 		= 'Por favor, preencha o campo de e-mail';
$lang['invalidEmail'] 		= 'Por favor, verifique a digitação.';
$lang['invalidEmail2'] 		= 'não é um endereço de e-mail válido.';
$lang['existingEmail'] 		= 'O e-mail';
$lang['existingEmail2'] 	= 'já consta na nossa lista e será avisado.';
$lang['emptyName'] 			= 'Por favor, preencha o campo de nome';
$lang['newSite'] 			= 'Novo site em';
$lang['soon']	 			= 'breve…';
$lang['close'] 				= 'Fechar';
$lang['success'] 			= 'Oba! Você está inscrito e será avisado no lançamento.';
$lang['connectError'] 		= 'Houve uma falha na comunicação com o servidor. Você está conectado? Por favor tente novamente.';
$lang['logoAlt'] 			= 'Logotipo';
$lang['titleSoon'] 			= 'Falta pouco!';
$lang['titleH2'] 			= "O novo site <strong>$siteName</strong> está quase pronto.";
$lang['titleH2Date'] 		= "Previsão de lançamento em $when.";
$lang['legend'] 			= "Quer ser avisado quando o site for lançado?";
$lang['email'] 				= "E-mail";
$lang['spamAlert'] 			= "Garantimos usar seu e-mail apenas para o aviso. Também odiamos SPAM.";
$lang['name'] 				= "Nome";
$lang['optional'] 			= "Opcional";
$lang['submit'] 			= "Sim. Quero ser avisado.";

}

